source "https://rubygems.org"

gem "rails", "~> 7.2.0"
gem "pg"
gem "puma"
gem "devise"
gem "pundit"
gem "sidekiq"
gem "turbo-rails"
gem "stimulus-rails"

group :development, :test do
  gem "rspec-rails"
  gem "factory_bot_rails"
end
