# frozen_string_literal: true

require "fileutils"
require "set"

module RailsAiContext
  module Install
    # Removing the context files of an AI tool the user dropped. All three
    # install entries prompt about this in their own voice; what they do once
    # the user says yes is the same work, and used to be three copies of it.
    module Cleanup
      module_function

      # The block SectionMarkerWriter manages inside a root context file.
      BEGIN_MARKER = "<!-- BEGIN rails-ai-context -->"
      MANAGED_BLOCK = /#{BEGIN_MARKER}.*?<!-- END rails-ai-context -->(?:\r?\n)?/m

      # The line a split rules file generated whole carries.
      GENERATED_NOTE = "Auto-generated by rails-ai-context. Do not edit manually."
      GENERATED_LINE = /^> #{Regexp.escape(GENERATED_NOTE)}\r?$/

      # Removes what this gem generated and nothing the user wrote: the named
      # rule files inside a rules directory, the managed block inside a root
      # file, and a file generated whole.
      #
      # @param tools [Array<Symbol>] the AI tools being dropped
      # @param keeping [Array<Symbol>] the tools still selected, whose files
      #   must survive even when a dropped tool names the same path
      # @param root [String, Pathname] project root
      # @return [Hash] { removed: [paths], trimmed: [paths], kept: [paths], failed: [paths] }.
      #   A directory carries a trailing slash. `trimmed` files lost their
      #   managed block and kept the user's lines; `kept` files hold nothing
      #   this gem generated. rm swallows its errors, so a path is only
      #   reported removed once it is gone.
      def remove(tools:, keeping:, root:)
        kept = Array(keeping).flat_map { |key| AiTool.find(key)&.context_paths || [] }.to_set
        outcome = { removed: [], trimmed: [], kept: [], failed: [] }

        Array(tools).each do |key|
          tool = AiTool.find(key) or next
          tool.context_paths.each do |relative|
            next if kept.include?(relative)

            if File.directory?(File.join(root.to_s, relative))
              remove_rule_files(tool, relative, root, outcome)
            else
              remove_generated(relative, root, outcome)
            end
          end
        end

        outcome
      end

      # A symlink is somebody's own arrangement, and writing through one edits
      # a file this run was not asked about.
      def remove_rule_files(tool, dir, root, outcome)
        full = File.join(root.to_s, dir)
        return if File.symlink?(full)

        names = Array(tool.rule_files) + tool.legacy_paths.select { |path| File.dirname(path) == dir }.map { |path| File.basename(path) }
        names.each { |name| delete(File.join(dir, name), root, outcome) }
        return unless Dir.empty?(full)

        Dir.rmdir(full)
        outcome[:removed] << "#{dir}/"
      rescue SystemCallError
        outcome[:failed] << "#{dir}/"
      end
      private_class_method :remove_rule_files

      # Bytes in, bytes out: the markers are ASCII, and the user's lines may not be valid UTF-8.
      def remove_generated(relative, root, outcome)
        full = File.join(root.to_s, relative)
        return unless File.file?(full) || File.symlink?(full)
        return outcome[:kept] << relative if File.symlink?(full)

        content = File.binread(full)
        rest = content.gsub(MANAGED_BLOCK, "")
        # The writer puts one blank line under a block it prepends to a file that was already there.
        rest = rest.sub(/\A\r?\n/, "") if content.start_with?(BEGIN_MARKER)
        if rest == content
          content.match?(GENERATED_LINE) ? delete(relative, root, outcome) : outcome[:kept] << relative
        elsif rest.strip.empty?
          delete(relative, root, outcome)
        else
          File.binwrite(full, rest)
          outcome[:trimmed] << relative
        end
      rescue SystemCallError
        outcome[:failed] << relative
      end
      private_class_method :remove_generated

      def delete(relative, root, outcome)
        full = File.join(root.to_s, relative)
        return unless File.file?(full) && !File.symlink?(full)

        FileUtils.rm_f(full)
        (File.exist?(full) ? outcome[:failed] : outcome[:removed]) << relative
      end
      private_class_method :delete
    end
  end
end
