# frozen_string_literal: true

module RailsAiContext
  module Serializers
    # Shared rendering methods for compact-mode serializers (Claude, OpenCode).
    # Include in any serializer that has a `context` reader and includes
    # StackOverviewHelper and TestCommandDetection.
    module CompactSerializerHelper
      include CountPhrase
      include ToolGuideHelper

      private

      # CopilotSerializer overrides this with its own title.
      def context_title
        "AI Context"
      end

      def render_header
        lines = [
          "# #{context[:app_name]} - #{context_title}",
          "",
          "> Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}",
          "> Generated by rails-ai-context v#{RailsAiContext::VERSION}"
        ]
        if (notice = SectionFacts.static_notice(context))
          lines << "> #{notice}"
        end
        lines << ""
        lines
      end

      def render_stack_overview
        lines = [ "## Stack" ]

        if (db_line = SectionFacts.database_line(context))
          lines << db_line
        end
        if (models_line = SectionFacts.models_line(context))
          lines << models_line
        end

        routes = Payload.section(context, :routes)
        lines << "- Routes: #{RouteCoverage.summary(routes)}" if routes

        jobs = Payload.section(context, :jobs)
        if jobs
          job_count = jobs[:jobs]&.size || 0
          worker_count = jobs[:workers]&.size || 0
          mailer_count = jobs[:mailers]&.size || 0
          channel_count = jobs[:channels]&.size || 0
          parts = []
          parts << count_phrase(job_count, "job") if job_count > 0
          parts << count_phrase(worker_count, "Sidekiq worker") if worker_count > 0
          parts << count_phrase(mailer_count, "mailer") if mailer_count > 0
          parts << count_phrase(channel_count, "channel") if channel_count > 0
          lines << "- Async: #{parts.join(', ')}" if parts.any?
        end

        if (migrations_line = SectionFacts.migrations_line(context))
          lines << migrations_line
        end

        lines.concat(full_preset_stack_lines)

        lines << ""
        lines
      end

      def render_key_models
        models = Payload.models(context)
        return [] unless models.any?

        max_show = 15
        lines = [ "## Key models (#{models.size} total, most connected first)" ]
        ranked = Payload.models_by_connection(models)
        ranked.first(max_show).each do |name|
          data = models[name]
          if (unread = SectionFacts.unread_row("- **#{name}**", data))
            lines << unread
            next
          end

          assoc_count = (data[:associations] || []).size
          val_count = (data[:validations] || []).size
          top_assocs = SectionFacts.associations_list(data).join(", ")
          line = "- **#{name}**"
          line += " (#{assoc_count}a, #{val_count}v)" if assoc_count > 0 || val_count > 0
          line += " - #{top_assocs}" if top_assocs && !top_assocs.empty?
          lines << line
          extras = model_extras_line(data)
          lines << extras if extras
        end
        if models.size > max_show
          use = " (use #{tool_named("rails_get_model_details")})" if served?("rails_get_model_details")
          lines << "- _...#{models.size - max_show} more#{use}_"
        end
        lines << ""
        lines
      end

      def render_notable_gems
        notable = Payload.notable_gems(context)
        return [] if notable.empty?

        lines = [ "## Gems" ]
        grouped = notable.group_by { |g| g[:category]&.to_s || "other" }
        grouped.each do |category, gem_list|
          names = gem_list.map { |g| g[:name] }.join(", ")
          lines << "- **#{category}**: #{names}"
        end
        lines << ""
        lines
      end

      def render_commands(root = project_root)
        server = AppCommands.server(root)
        migrate = AppCommands.migrate(root)
        lines = [ "## Commands" ]
        lines << "- `#{server}` - #{server == 'bin/dev' ? 'start dev server' : 'start the app'}" if server
        lines << "- `#{detect_test_command}` - run tests"
        lines << "- `#{migrate}` - run pending migrations" if migrate
        lines << ""
      end

      def render_warnings
        SectionFacts.warnings(context)
      end

      # Where the cut detail is: the tools, as the mode reaches them.
      def trim_note
        "_Context trimmed. Use #{tools_noun} for full details._"
      end

      # Counts non-blank physical lines. `head` (the title block) and `keep`
      # (the trailing how-to-behave sections: commands, warnings, rules, the
      # tools guide and its protocol) are never cut. An over-budget file
      # loses the data between them, which the tools answer in full, down to
      # none of it, so a budget smaller than the kept sections leaves just
      # them: the guide is what makes a compact file worth reading.
      def enforce_max_lines(lines, head: [], keep: [])
        # The BEGIN/END markers the writer adds count against the budget.
        max = RailsAiContext.configuration.claude_max_lines - SectionMarkerWriter::MARKER_LINES
        head = physical(head)
        body = physical(lines)
        tail = physical(keep)
        fixed = content_count(head) + content_count(tail)
        return (head + body + tail).join("\n") if fixed + content_count(body) <= max

        separator = tail.empty? ? [] : [ "" ]
        (head + truncate(body, max - 1 - fixed) + separator + tail).join("\n")
      end

      def physical(lines)
        lines.join("\n").split("\n", -1)
      end

      def content_count(lines)
        lines.count { |line| !line.strip.empty? }
      end

      # The first `budget` content lines, with the trim note marking the cut.
      def truncate(lines, budget)
        kept = []
        lines.each do |line|
          next kept << line if line.strip.empty?
          break if budget <= 0

          budget -= 1
          kept << line
        end
        # A block cut open renders the note and everything after it as code,
        # so an unclosed fence goes whole; its `#` lines were never headings.
        open_at = nil
        kept.each_with_index { |line, i| open_at = open_at.nil? ? i : nil if fence?(line) }
        kept = kept[0...open_at] if open_at
        # A heading whose body was cut claims content that is not there, so it goes too,
        # nested headings and separators included.
        kept.pop while kept.any? && (kept.last.strip.empty? || heading?(kept.last))
        kept << "" if kept.any?
        kept << trim_note
      end

      def heading?(line)
        line.lstrip.start_with?("#")
      end

      def fence?(line)
        line.lstrip.start_with?("```", "~~~")
      end

      # Architecture / conventions section - moved from ClaudeSerializer so
      # Cursor (.cursorrules) and any future compact serializer can reuse.
      # The architecture and pattern lines need the booted conventions; the
      # services and jobs lines are read from files, so every tier has them.
      def render_architecture
        lines = []
        if Payload.section(context, :conventions)
          arch_labels = arch_labels_hash
          pattern_labels = pattern_labels_hash
          Payload.architecture(context).each { |p| lines << "- #{arch_labels[p] || p}" }
          Payload.patterns(context).first(8).each { |p| lines << "- #{pattern_labels[p] || p}" }
        end

        # The scan decides, so services under a configured extra path show wherever
        # the conventions walk looked.
        names = []
        services = service_names
        names << "**Services:** #{services.join(', ')}" if services.any?
        jobs = job_names
        names << "**Jobs:** #{jobs.join(', ')}" if jobs.any?

        # The blank line sets the names apart from a pattern list. With no list
        # above them - the static tier reads no conventions - it left the
        # heading standing over nothing.
        lines << "" if lines.any? && names.any?
        lines.concat(names)
        return [] if lines.empty?

        [ "## Architecture", *lines, "" ]
      end

      # Footer rules section - also moved from ClaudeSerializer.
      def render_footer
        test_cmd = detect_test_command
        lines = [ "## Rules" ]
        lines << "- Run `#{test_cmd}` after changes"
        lines << "- Do NOT re-read files to verify edits - trust your Edit, validate syntax only"

        if Payload.section(context, :conventions)
          arch = Payload.architecture(context)
          lines << "- Follow #{arch.join(' + ')} architecture" if arch.any?
          patterns = Payload.patterns(context)
          lines << "- Use service objects for business logic" if patterns.include?("service_objects")
          lines << "- Use form objects for complex forms" if patterns.include?("form_objects")
          lines << "- Use query objects for complex queries" if patterns.include?("query_objects")
        end

        stimulus = Payload.section(context, :stimulus)
        if Payload.stimulus_controllers(context).any? || stimulus&.dig(:total_controllers)&.positive?
          lines << if stimulus&.dig(:auto_registers)
            "- Stimulus controllers auto-register - no manual import in controllers/index.js needed"
          else
            "- Stimulus controllers are not auto-loaded from `app/javascript/controllers` - register a new one the way the existing ones are"
          end
        end

        before_actions = detect_before_actions
        lines << "- Global before_actions: #{before_actions.join(', ')}" if before_actions.any?

        lines << ""
        lines
      end

      # The compact pipeline behind CLAUDE.md, AGENTS.md, .cursorrules and copilot-instructions.md.
      def render_compact_rules
        data = render_stack_overview + render_key_models + render_notable_gems + render_architecture
        instructions = render_commands + render_warnings + render_footer + render_tools_guide_compact
        enforce_max_lines(data, head: render_header, keep: instructions)
      end
    end
  end
end
