# frozen_string_literal: true

module RailsAiContext
  module Serializers
    # Generates GitHub Copilot instructions.
    # In :compact mode (default), renders the shared compact rules under the
    # `claude_max_lines` budget. In :full mode, delegates to MarkdownSerializer.
    class CopilotSerializer < Base
      include TestCommandDetection
      include StackOverviewHelper
      include ToolGuideHelper
      include CompactSerializerHelper
      include ContextModeDispatch

      private

      def full_serializer_class
        FullCopilotSerializer
      end

      def context_title
        "Copilot Context"
      end

      def render_compact
        render_compact_rules
      end
    end

    # Internal: full-mode Copilot serializer (wraps MarkdownSerializer)
    class FullCopilotSerializer < MarkdownSerializer
      include FullSerializerBehavior

      private

      def header
        <<~MD
          # #{context[:app_name]} - Copilot Instructions

          > Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}
          > Auto-generated by rails-ai-context v#{RailsAiContext::VERSION}
          #{tier_note}
          Use this context to generate code that fits this project's structure and patterns.
        MD
      end
    end
  end
end
