# frozen_string_literal: true

module RailsAiContext
  module Serializers
    # Generates AI-friendly markdown context files from introspection data.
    # Outputs: CLAUDE.md (for Claude Code), .cursorrules, .windsurfrules, etc.
    class MarkdownSerializer
      attr_reader :context

      def initialize(context)
        @context = context
      end

      # @return [String] full markdown document
      def call
        sections = []
        sections << header
        sections << app_overview
        sections << schema_section if context[:schema]
        sections << models_section if context[:models]
        sections << routes_section if context[:routes]
        sections << jobs_section if context[:jobs]
        sections << gems_section if context[:gems]
        sections << conventions_section if context[:conventions]
        sections << footer
        sections.compact.join("\n\n")
      end

      private

      def header
        <<~MD
          # #{context[:app_name]} — AI Context

          > Auto-generated by rails-ai-context v#{RailsAiContext::VERSION}
          > Generated: #{context[:generated_at]}
          > Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}

          This file gives AI assistants (Claude Code, Cursor, Copilot) deep context
          about this Rails application's structure, patterns, and conventions.
        MD
      end

      def app_overview
        conv = context[:conventions] || {}
        arch = conv[:architecture] || []
        patterns = conv[:patterns] || []

        lines = [ "## Overview" ]
        lines << "- **Architecture:** #{arch.join(', ')}" if arch.any?
        lines << "- **Patterns:** #{patterns.join(', ')}" if patterns.any?
        lines.join("\n")
      end

      def schema_section
        schema = context[:schema]
        return if schema[:error]

        lines = [ "## Database Schema (#{schema[:total_tables]} tables)" ]
        schema[:tables]&.each do |name, data|
          cols = (data[:columns] || []).map { |c| "`#{c[:name]}` (#{c[:type]})" }.join(", ")
          lines << "### #{name}"
          lines << cols
        end
        lines.join("\n\n")
      end

      def models_section
        models = context[:models]
        return if models.is_a?(Hash) && models[:error]

        lines = [ "## Models (#{models.size})" ]
        models.each do |name, data|
          next if data[:error]
          assocs = (data[:associations] || []).map { |a| "#{a[:type]} :#{a[:name]}" }.join(", ")
          lines << "### #{name}"
          lines << "- Table: `#{data[:table_name]}`" if data[:table_name]
          lines << "- Associations: #{assocs}" if assocs.present?
          if data[:validations]&.any?
            vals = data[:validations].map { |v| "#{v[:kind]} on #{v[:attributes].join(', ')}" }.join("; ")
            lines << "- Validations: #{vals}"
          end
          lines << "- Enums: #{data[:enums].keys.join(', ')}" if data[:enums]&.any?
        end
        lines.join("\n")
      end

      def routes_section
        routes = context[:routes]
        return if routes[:error]

        lines = [ "## Routes (#{routes[:total_routes]} total)" ]
        routes[:by_controller]&.sort&.each do |ctrl, actions|
          lines << "### #{ctrl}"
          actions.each do |r|
            lines << "- `#{r[:verb]} #{r[:path]}` → #{r[:action]}"
          end
        end
        lines.join("\n")
      end

      def jobs_section
        jobs = context[:jobs]
        parts = []

        if jobs[:jobs]&.any?
          parts << "## Background Jobs"
          jobs[:jobs].each { |j| parts << "- `#{j[:name]}` (queue: #{j[:queue]})" }
        end

        if jobs[:mailers]&.any?
          parts << "## Mailers"
          jobs[:mailers].each { |m| parts << "- `#{m[:name]}`: #{m[:actions].join(', ')}" }
        end

        if jobs[:channels]&.any?
          parts << "## Action Cable Channels"
          jobs[:channels].each { |c| parts << "- `#{c[:name]}`" }
        end

        parts.join("\n") if parts.any?
      end

      def gems_section
        gems = context[:gems]
        return if gems[:error]

        notable = gems[:notable_gems] || []
        return if notable.empty?

        lines = [ "## Notable Gems" ]
        notable.group_by { |g| g[:category] }.sort.each do |cat, group|
          lines << "### #{cat.capitalize}"
          group.each { |g| lines << "- **#{g[:name]}** (#{g[:version]}): #{g[:note]}" }
        end
        lines.join("\n")
      end

      def conventions_section
        conv = context[:conventions]
        return unless conv[:directory_structure]&.any?

        lines = [ "## Project Structure" ]
        conv[:directory_structure].sort.each do |dir, count|
          lines << "- `#{dir}/` — #{count} files"
        end
        lines.join("\n")
      end

      def footer
        <<~MD
          ---
          _This context file is auto-generated. Run `rails ai:context` to regenerate._
        MD
      end
    end
  end
end
