# frozen_string_literal: true

module RailsAiContext
  module Serializers
    # Generates AI-friendly markdown context files from introspection data.
    # Outputs: CLAUDE.md (for Claude Code), copilot-instructions.md, etc.
    #
    # Full mode's root files are the only file OpenCode and Codex load whole,
    # so they close with the tools guide and the protocol the compact files
    # carry, not the data alone.
    class MarkdownSerializer < Base
      include TestCommandDetection
      include StackOverviewHelper
      include ToolGuideHelper

      MARKDOWN_SPECIAL_CHARS = /([\\`*_{\}\[\]()+\-#.!~|])/

      SECTIONS = %i[
        schema models routes jobs gems conventions controllers views stimulus turbo active_storage
        action_text i18n config assets auth api tests rake_tasks devops action_mailbox
        migrations seeds middleware engines multi_database
      ].freeze

      # @return [String] full markdown document
      def call
        sections = [ header, app_overview ]
        SECTIONS.each { |key| sections << send("#{key}_section") if Payload.section(context, key) }
        sections << warnings_section if context[:_warnings]&.any?
        sections << rules_section
        sections << render_tools_guide_compact.join("\n").rstrip
        sections << footer
        sections.compact.join("\n\n")
      end

      private

      def header
        <<~MD
          # #{context[:app_name]} - AI Context

          > Auto-generated by rails-ai-context v#{RailsAiContext::VERSION}
          > Generated: #{context[:generated_at]}
          > Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}
          #{tier_note}
          This file gives AI assistants (Claude Code, Cursor, Copilot, OpenCode, Codex) deep context
          about this Rails application's structure, patterns, and conventions.
        MD
      end

      # Rendered inside a quoted header block, so it carries the marker with it.
      def tier_note
        notice = SectionFacts.static_notice(context)
        notice ? "> #{notice}\n" : ""
      end

      def app_overview
        arch = Payload.architecture(context)
        patterns = Payload.patterns(context)

        arch_labels = arch_labels_hash
        pattern_labels = pattern_labels_hash

        lines = []
        lines << "- **Architecture:** #{arch.map { |a| arch_labels[a] || a }.join(', ')}" if arch.any?
        lines << "- **Patterns:** #{patterns.map { |p| pattern_labels[p] || p }.join(', ')}" if patterns.any?
        # The static tier has no conventions, and a heading over nothing reads as a section that failed.
        [ "## Overview", *lines ].join("\n") if lines.any?
      end

      # Each column with its type and default, then the table's indexes and
      # foreign keys: the facts a migration has to agree with.
      def schema_section
        schema = Payload.section(context, :schema)

        lines = [ "## Database Schema (#{Introspectors::SchemaConventions.relations_phrase(schema[:tables])})" ]
        schema[:tables]&.each do |name, data|
          lines << "### #{escape_markdown(name)}"
          lines << ([ (data[:columns] || []).map { |c| column_text(c) }.join(", ") ] + table_key_lines(data)).join("\n")
        end
        lines.join("\n\n")
      end

      def column_text(column)
        details = [ column[:type], ("default #{column[:default] == "" ? '""' : column[:default]}" unless column[:default].nil?) ].compact
        details.any? ? "`#{column[:name]}` (#{details.join(', ')})" : "`#{column[:name]}`"
      end

      def table_key_lines(data)
        indexes = Array(data[:indexes]).map do |index|
          columns = Array(index[:columns]).join("+")
          where = Introspectors::SchemaConventions.where_clause(index[:where])
          index[:unique] ? "#{columns} (unique#{where})" : "#{columns}#{where}"
        end
        foreign_keys = Array(data[:foreign_keys]).map do |fk|
          "#{Introspectors::SchemaConventions.key_text(fk[:column])} → #{fk[:to_table]}"
        end
        lines = []
        lines << "- Indexes: #{indexes.join('; ')}" if indexes.any?
        lines << "- Foreign keys: #{foreign_keys.join('; ')}" if foreign_keys.any?
        lines
      end

      def models_section
        models = Payload.models(context)
        return if models.empty?

        lines = [ "## Models (#{models.size})" ]
        models.each do |name, data|
          lines << "### #{escape_markdown(name)}"
          if (unread = SectionFacts.unread_marker(data))
            lines << "- #{unread}"
            next
          end

          assocs = SectionFacts.associations_list(data).join(", ")
          lines << "- Table: `#{data[:table_name]}`" if data[:table_name]
          concerns = ConcernMembership.app_owned(data[:concerns], project_root)
          lines << "- Concerns: #{concerns.join(', ')}" if concerns.any?
          lines << "- Associations: #{assocs}" if assocs.present?
          if data[:validations]&.any?
            vals = data[:validations].map { |v| [ v[:kind], SectionFacts.validation_target(v) ].reject(&:empty?).join(" ") }.join("; ")
            lines << "- Validations: #{vals}"
          end
          lines.concat(model_detail_lines(data))
        end
        lines.join("\n")
      end

      # What the compact files and the models rule file already state, which
      # the "everything" file left out.
      def model_detail_lines(data)
        lines = []
        scopes = scope_names(Array(data[:scopes]))
        lines << "- Scopes: #{scopes.join(', ')}" if scopes.any?
        callbacks = data[:callbacks].is_a?(Hash) ? data[:callbacks] : {}
        if callbacks.any?
          lines << "- Callbacks: #{callbacks.map { |kind, names| "#{kind} #{Array(names).map { |n| callback_name(n) }.join(', ')}" }.join('; ')}"
        end
        enums = data[:enums].is_a?(Hash) ? data[:enums] : Array(data[:enums]).to_h { |name| [ name, nil ] }
        lines << "- Enums: #{enums.map { |name, values| values ? "#{name} (#{SectionFacts.enum_values(values)})" : name }.join('; ')}" if enums.any?
        Array(data[:constants]).each { |c| lines << "- #{c[:name]}: #{Array(c[:values]).join(', ')}" if c.is_a?(Hash) }
        lines
      end

      def callback_name(callback)
        callback.is_a?(Hash) ? (callback[:method] || callback[:name]).to_s : callback.to_s
      end

      def routes_section
        routes = Payload.section(context, :routes)
        return unless routes

        # The app's own routes, each PATCH/PUT pair one entry as the count has
        # it. What Rails' engines draw (Active Storage, Action Mailbox, Turbo)
        # is counted, not listed: the tools leave it out the same way.
        lines = [ "## Routes", "", "#{RouteCoverage.summary(routes)}." ]
        RouteCoverage.app_controllers(routes).sort.each do |ctrl, actions|
          lines << "### #{escape_markdown(ctrl)}"
          actions.each do |r|
            lines << "- `#{r[:verb]} #{r[:path]}` → #{r[:action]}"
          end
        end
        framework = RouteCoverage.by_controller(routes).keys.select { |ctrl| RouteCoverage.framework_controller?(ctrl) }
        if framework.any?
          owners = framework.map { |ctrl| ctrl.split("/").first }.uniq.sort
          lines << "" << "_Plus #{CountPhrase.call(RouteCoverage.framework_route_count(routes), 'framework route')} (#{owners.join(', ')}), not listed._"
        end
        Array(routes[:engine_routes]).each do |group|
          Array(group[:routes]).group_by { |r| r[:controller].to_s }.sort.each do |ctrl, actions|
            lines << "### #{escape_markdown(ctrl)} (in #{group[:engine]}'s table, not in the total)"
            actions.each { |r| lines << "- `#{r[:verb]} #{r[:path]}` → #{r[:action]}" }
          end
        end
        lines.join("\n")
      end

      def jobs_section
        jobs = Payload.section(context, :jobs)
        parts = []

        if jobs[:jobs]&.any?
          parts << "## Background Jobs"
          jobs[:jobs].each { |j| parts << "- `#{j[:name]}` (queue: #{j[:queue]})" }
        end

        if jobs[:mailers]&.any?
          parts << "## Mailers"
          jobs[:mailers].each { |m| parts << "- `#{m[:name]}`: #{m[:actions].join(', ')}" }
        end

        if jobs[:channels]&.any?
          parts << "## Action Cable Channels"
          jobs[:channels].each { |c| parts << "- `#{c[:name]}`" }
        end

        parts.join("\n") if parts.any?
      end

      def gems_section
        notable = Payload.notable_gems(context)
        return if notable.empty?

        lines = [ "## Notable Gems" ]
        notable.group_by { |g| g[:category] }.sort.each do |cat, group|
          lines << "### #{cat.capitalize}"
          group.each { |g| lines << "- **#{g[:name]}** (#{g[:version]}): #{g[:note]}" }
        end
        lines.join("\n")
      end

      def conventions_section
        conv = Payload.section(context, :conventions)
        return unless conv && conv[:directory_structure]&.any?

        lines = [ "## Project Structure" ]
        conv[:directory_structure].sort.each do |dir, count|
          lines << "- `#{dir}/` - #{count_phrase(count, "file")}"
        end
        lines.join("\n")
      end

      def controllers_section
        controllers = Payload.app_controllers(context)
        return if controllers.empty?

        lines = [ "## Controllers (#{controllers.size})" ]
        controllers.each do |name, info|
          lines << "### #{escape_markdown(name)}"
          lines << "- Parent: `#{info[:parent_class]}`" if info[:parent_class]
          lines << "- API controller: yes" if info[:api_controller]
          lines << "- Actions: #{info[:actions]&.join(', ')}" if info[:actions]&.any?
          lines.concat(SectionFacts.controller_summary_lines(info, ctx: context, name: name))
        end
        lines.join("\n")
      end

      def views_section
        data = Payload.section(context, :views)

        lines = [ "## Views" ]
        layouts = (data[:layouts] || []).map { |layout| layout.is_a?(Hash) ? layout[:name] : layout }
        lines << "- Layouts: #{layouts.join(', ')}" if layouts.any?
        lines << "- Template engines: #{data[:template_engines].join(', ')}" if data[:template_engines]&.any?

        if data[:templates]&.any?
          lines << "### Templates by controller"
          data[:templates].each do |ctrl, templates|
            lines << "- `#{ctrl}/`: #{templates.join(', ')}"
          end
        end

        if data[:helpers]&.any?
          lines << "### Helpers"
          data[:helpers].each do |h|
            methods = Array(h[:methods])
            lines << (methods.any? ? "- `#{h[:file]}`: #{methods.join(', ')}" : "- `#{h[:file]}` (no methods)")
          end
        end

        lines << "- View components: #{data[:view_components].size}" if data[:view_components]&.any?
        lines.join("\n")
      end

      def stimulus_section
        controllers = Payload.stimulus_controllers(context).select { |c| c.is_a?(Hash) && c[:name] }
        return if controllers.empty?

        lines = [ "## Stimulus Controllers (#{controllers.size})" ]
        controllers.each do |c|
          values = c[:values].is_a?(Hash) ? c[:values].map { |name, type| "#{name} (#{type})" } : Array(c[:values])
          parts = { "targets" => Array(c[:targets]), "values" => values, "actions" => Array(c[:actions]),
                    "outlets" => Array(c[:outlets]), "classes" => Array(c[:classes]) }
            .reject { |_, list| list.empty? }.map { |kind, list| "#{kind}: #{list.join(', ')}" }
          lines << "- `#{c[:name]}`#{" - #{parts.join('; ')}" if parts.any?}"
        end
        lines.join("\n")
      end

      def turbo_section
        data = Payload.section(context, :turbo)
        return if data[:turbo_frames]&.empty? && data[:turbo_streams]&.empty? && data[:model_broadcasts]&.empty?

        lines = [ "## Hotwire / Turbo" ]
        if data[:turbo_frames]&.any?
          lines << "### Turbo Frames"
          data[:turbo_frames].each { |f| lines << "- `#{f[:id]}` in #{f[:file]}" }
        end
        if data[:turbo_streams]&.any?
          lines << "### Turbo Stream Templates"
          data[:turbo_streams].each { |t| lines << "- `#{t}`" }
        end
        if data[:model_broadcasts]&.any?
          lines << "### Model Broadcasts"
          data[:model_broadcasts].group_by { |b| b[:model] }.each do |model, hits|
            lines << "- `#{model}`: #{hits.map { |b| b[:macro] }.uniq.join(', ')}"
          end
        end
        lines.join("\n")
      end

      def active_storage_section
        data = Payload.section(context, :active_storage)
        return unless data[:attachments]&.any?

        lines = [ "## Active Storage" ]
        data[:attachments].each { |a| lines << "- `#{a[:model]}` #{a[:type]} :#{a[:name]}" }
        lines << "- Storage services: #{data[:storage_services].join(', ')}" if data[:storage_services]&.any?
        lines.join("\n")
      end

      def action_text_section
        data = Payload.section(context, :action_text)
        return unless data[:rich_text_fields]&.any?

        lines = [ "## Action Text" ]
        data[:rich_text_fields].each { |f| lines << "- `#{f[:model]}` has_rich_text :#{f[:field]}" }
        lines.join("\n")
      end

      def i18n_section
        data = Payload.section(context, :i18n)

        lines = [ "## Internationalization" ]
        lines << "- Default locale: #{data[:default_locale]}"
        lines << "- #{SectionFacts.available_locales_label(data)}: #{data[:available_locales]&.join(', ')}"
        if data[:total_locale_files]&.positive?
          lines << "- Locale files: #{data[:total_locale_files]}#{SectionFacts.unread_locale_note(data)}"
        end
        lines.join("\n")
      end

      def config_section
        data = Payload.section(context, :config)

        lines = [ "## Configuration" ]
        lines << "- Cache store: #{data[:cache_store]}" if data[:cache_store]
        lines << "- Session store: #{data[:session_store]}" if data[:session_store]
        lines << "- Timezone: #{data[:timezone]}" if data[:timezone].present?
        if data[:initializers]&.any?
          lines << "- Initializers: #{data[:initializers].join(', ')}"
        end
        lines.join("\n")
      end

      def assets_section
        data = Payload.section(context, :assets)

        lines = [ "## Asset Pipeline" ]
        lines << "- Pipeline: #{data[:pipeline]}" if data[:pipeline]
        lines << "- JS bundler: #{data[:js_bundler]}" if data[:js_bundler]
        lines << "- CSS framework: #{data[:css_framework]}" if data[:css_framework]
        if data[:importmap_pins]&.any?
          lines << "- Importmap pins: #{data[:importmap_pins].join(', ')}"
        end
        lines.join("\n")
      end

      def auth_section
        data = Payload.section(context, :auth)

        authn = data[:authentication] || {}
        authz = data[:authorization] || {}
        return if authn.empty? && authz.empty?

        lines = [ "## Authentication & Authorization" ]
        if authn[:devise]
          lines << "### Devise"
          authn[:devise].each { |d| lines << "- `#{d[:model]}`: #{d[:matches].join(', ')}" }
        end
        lines << "- Rails 8 built-in auth detected" if authn[:rails_auth]
        lines << "- Rodauth: #{Array(authn.dig(:rodauth, :classes)).join(', ').presence || 'rodauth-rails'}" if authn[:rodauth]
        lines << "- has_secure_password: #{authn[:has_secure_password].join(', ')}" if authn[:has_secure_password]
        Introspectors::AuthIntrospector.digest_sentences(authn).each { |sentence| lines << "- #{sentence}" }
        if authz[:pundit]
          lines << "### Pundit Policies"
          authz[:pundit].each { |p| lines << "- `#{p}`" }
        end
        if authz[:action_policy]
          lines << "### Action Policy Policies"
          authz[:action_policy].each { |p| lines << "- `#{p}`" }
        end
        if authz[:policies]
          lines << "### Policy Classes (app/policies)"
          authz[:policies].each { |p| lines << "- `#{p}`" }
        end
        lines << "- CanCanCan: Ability class detected" if authz[:cancancan]
        lines << "- Ability class: `#{authz[:ability_class]}`" if authz[:ability_class]
        lines.join("\n")
      end

      def api_section
        data = Payload.section(context, :api)

        lines = [ "## API Layer" ]
        lines << "- API-only mode: #{data[:api_only]}"
        if data[:api_versioning]&.any?
          lines << "- API versions: #{data[:api_versioning].join(', ')}"
        end
        if data[:serializers]&.any?
          lines << "- Jbuilder templates: #{data[:serializers][:jbuilder]}" if data[:serializers][:jbuilder]
          lines << "- RABL templates: #{data[:serializers][:rabl]}" if data[:serializers][:rabl]
          if data[:serializers][:serializer_classes]&.any?
            lines << "- Serializers: #{data[:serializers][:serializer_classes].join(', ')}"
          end
        end
        if data[:graphql]
          lines << "### GraphQL"
          lines << "- Types: #{data[:graphql][:types]}, Mutations: #{data[:graphql][:mutations]}"
        end
        lines.join("\n")
      end

      def tests_section
        data = Payload.section(context, :tests)

        lines = [ "## Testing" ]
        lines << "- Framework: #{data[:framework]}"
        lines << "- Factories: #{TestFramework.factory_location(data[:factories])}" if data[:factories]
        lines << "- Fabricators: #{data[:fabricators][:location]} (#{count_phrase(data[:fabricators][:count], "file")})" if data[:fabricators]
        lines << "- Fixtures: #{data[:fixtures][:location]} (#{TestFramework.fixture_phrase(data[:fixtures])})" if data[:fixtures]
        lines << "- System tests: #{data[:system_tests][:location]}" if data[:system_tests]
        lines << "- CI: #{data[:ci_config].join(', ')}" if data[:ci_config]&.any?
        lines << "- Coverage: #{data[:coverage]}" if data[:coverage]
        lines.join("\n")
      end

      def rake_tasks_section
        data = Payload.section(context, :rake_tasks)
        return unless data[:tasks]&.any?

        lines = [ "## Rake Tasks" ]
        data[:tasks].each do |task|
          desc = task[:description] ? " - #{task[:description]}" : ""
          lines << "- `#{task[:name]}`#{desc}"
        end
        lines.join("\n")
      end

      def devops_section
        data = Payload.section(context, :devops)

        lines = [ "## DevOps" ]
        lines << "- Deployment: #{data[:deployment]}" if data[:deployment]
        if data[:docker]
          lines << "- Docker: #{data[:docker][:multi_stage] ? 'multi-stage' : 'single-stage'} build"
        end
        # Last and only with a line under it: a bare "### Puma" took the
        # deployment lines after it for its own.
        puma = data[:puma].is_a?(Hash) ? data[:puma] : {}
        puma_lines = []
        puma_lines << "- Threads: #{puma[:threads_min]}-#{puma[:threads_max]}" if puma[:threads_min]
        puma_lines << "- Workers: #{puma[:workers]}" if puma[:workers]
        lines.push("### Puma", *puma_lines) if puma_lines.any?
        lines.join("\n") if lines.size > 1
      end

      def action_mailbox_section
        data = Payload.section(context, :action_mailbox)
        return unless data[:mailboxes]&.any?

        lines = [ "## Action Mailbox" ]
        data[:mailboxes].each { |m| lines << "- `#{m[:name]}`" }
        lines.join("\n")
      end

      def migrations_section
        data = Payload.section(context, :migrations)

        lines = [ "## Migrations" ]
        lines << "- Total: #{data[:total]}"
        lines << "- Schema version: #{data[:schema_version]}" if data[:schema_version]

        pending = Payload.pending_migrations(context)
        if pending.any?
          lines << "### Pending Migrations (#{pending.size})"
          pending.each { |m| lines << "- `#{m[:version]}` #{m[:name]}" }
        end

        if data[:recent]&.any?
          lines << "### Recent Migrations"
          data[:recent].each do |m|
            actions = m[:actions]&.any? ? " (#{m[:actions].join(', ')})" : ""
            lines << "- `#{m[:version]}` #{m[:name]}#{actions}"
          end
        end

        lines.join("\n")
      end

      def seeds_section
        data = Payload.section(context, :seeds)

        lines = [ "## Database Seeds" ]
        if data[:seeds_file]
          lines << "- Seeds file: #{data[:seeds_file][:exists] ? 'exists' : 'missing'}"
          lines << "- Uses Faker: yes" if data[:seeds_file][:uses_faker]
          lines << "- Environment-conditional: yes" if data[:seeds_file][:environment_conditional]
        end
        lines << "- Models seeded: #{data[:models_seeded].join(', ')}" if data[:models_seeded]&.any?

        if data[:seed_files]&.any?
          lines << "### Seed Files"
          data[:seed_files].each { |f| lines << "- `#{f[:file]}`" }
        end

        lines.join("\n")
      end

      def middleware_section
        data = Payload.section(context, :middleware)

        inserted = Array(data[:middleware_from_initializers])
        custom = Array(data[:custom_middleware])

        lines = [ "## Custom Middleware" ]
        if custom.any?
          custom.each do |m|
            detail = "- `#{m[:class_name]}` (#{m[:file]})"
            detail += " - #{m[:detected_patterns].join(', ')}" if m[:detected_patterns]&.any?
            label = insertion_labels(inserted, m[:class_name])
            detail += " - #{label}" unless label.empty?
            lines << detail
          end
        else
          lines << "- No custom middleware in app/middleware/ or lib/middleware/"
        end
        if (errors_app = data[:exceptions_app])
          file = errors_app[:file] ? " (#{errors_app[:file]})" : ""
          lines << "- Exceptions app: `#{errors_app[:class_name]}`#{file}"
        end

        # A class the app does not own is a change to the stack, not one of
        # its own middlewares: a deletion, or a Rails middleware moved.
        named = custom.map { |m| m[:class_name] }
        rest = inserted.reject { |m| named.include?(m[:middleware]) }
        if rest.any?
          lines << "### Stack changes from the app's config"
          rest.each { |m| lines << "- `#{m[:middleware]}` #{stack_change_label(m)}" }
        end

        lines.join("\n")
      end

      # Every place the config puts a middleware the app also keeps a file
      # for, so the class is not listed twice and no change is dropped.
      def insertion_labels(inserted, class_name)
        inserted.select { |m| m[:middleware] == class_name }.map { |m| stack_change_label(m) }.join(", ")
      end

      def stack_change_label(entry)
        verb = case entry[:action]
        when "delete" then "removed"
        when "move_before", "move_after" then "moved (#{entry[:action]})"
        when "swap" then "swapped in (swap)"
        else "inserted (#{entry[:action]})"
        end
        "#{verb} in #{entry[:file]}"
      end

      def engines_section
        data = Payload.section(context, :engines)

        lines = [ "## Mounted Apps" ]
        if data[:mounted_engines]&.any?
          data[:mounted_engines].each do |e|
            desc = e[:description] ? " - #{e[:description]}" : ""
            at = e[:path] ? " at `#{e[:path]}`" : ""
            at += " (`#{e[:condition]}`)" if e[:condition]
            lines << "- `#{e[:engine]}`#{at}#{desc}"
          end
        else
          lines << "- Nothing mounted"
        end

        in_repo = Payload.in_repo_engines_with_models(context)
        if in_repo.any?
          lines << "" << "### In-Repo Engines (#{in_repo.size})"
          in_repo.each do |e|
            count = Payload.engine_model_phrase(e)
            lines << "- `#{e[:name]}` at `#{e[:path]}`#{count}"
          end
        end

        lines.join("\n")
      end

      def multi_database_section
        data = Payload.section(context, :multi_database)
        return unless data[:multi_db]

        lines = [ "## Multi-Database" ]
        if data[:databases]&.any?
          data[:databases].each do |db|
            replica = db[:replica] ? " (replica)" : ""
            lines << "- `#{db[:name]}` - #{SchemaAdapter.database_label(db) || "unknown"}#{replica}"
          end
        end

        if data[:model_connections]&.any?
          lines << "### Model Connections"
          data[:model_connections].each do |c|
            lines << "- `#{c[:model]}` → #{c[:connects_to] || 'custom connection'}#{" (only #{c[:condition]})" if c[:condition]}"
          end
        end

        lines.join("\n")
      end

      def warnings_section
        warnings = context[:_warnings]
        return if warnings.nil? || warnings.empty?

        lines = [ "## Warnings", "" ]
        lines << "The following sections were unavailable during introspection:"
        lines << ""
        warnings.each do |w|
          lines << "- **#{w[:introspector]}**: #{w[:error]}"
        end
        lines.join("\n")
      end

      # The AI tools' files carry their own (FullSerializerBehavior).
      def rules_section
        nil
      end

      def footer
        <<~MD
          ---
          _This context file is auto-generated. Run `#{RailsAiContext::InstallMode.command(:context)}` to regenerate._
        MD
      end

      def escape_markdown(text)
        return "" if text.nil?
        text.to_s.gsub(MARKDOWN_SPECIAL_CHARS, '\\\\\1')
      end
    end

    # Shared behavior for the full-mode serializers of the AI tools' root
    # files (FullClaudeSerializer, FullOpencodeSerializer, FullCopilotSerializer).
    # Provides the behavioral rules section and architecture summary.
    module FullSerializerBehavior
      private

      def rules_section
        rules = []
        rules << "## Behavioral Rules"
        rules << ""
        rules << "When working in this codebase:"
        rules << "- Follow existing patterns and conventions detected above"
        rules << "- Use the database schema as the source of truth for column names and types"
        rules << "- Respect existing associations and validations when modifying models"
        rules << "- Match the project's architecture style (#{architecture_summary})" if architecture_summary
        test_cmd = detect_test_command
        rules << "- Run `#{test_cmd}` after making changes to verify correctness"
        rules.join("\n")
      end

      def architecture_summary
        arch = Payload.architecture(context)
        arch.any? ? arch.join(", ") : nil
      end
    end
  end
end
