# frozen_string_literal: true

module RailsAiContext
  module Serializers
    # Generates per-directory AGENTS.md files for OpenCode's lazy-loading system.
    # When OpenCode's agent reads a file, it walks up the directory tree and
    # auto-loads any AGENTS.md it finds - acting as contextual split rules.
    #
    # Generated files:
    #   app/models/AGENTS.md      - model listing, loaded when editing models
    #   app/controllers/AGENTS.md - controller listing, loaded when editing controllers
    class OpencodeRulesSerializer
      include StackOverviewHelper

      attr_reader :context

      def initialize(context)
        @context = context
      end

      # @param output_dir [String] Rails root path
      # @return [Hash] { written: [paths], skipped: [paths] }
      RENDERERS = {
        "app/models/AGENTS.md" => :render_models_reference,
        "app/controllers/AGENTS.md" => :render_controllers_reference
      }.freeze

      def call(output_dir)
        files = {}

        # The split targets after the root file, per the table's convention.
        Install::AiTool.find(:opencode).context_paths.drop(1).each do |relative|
          filepath = File.join(output_dir, relative)
          next unless Dir.exist?(File.dirname(filepath))
          files[filepath] = send(RENDERERS.fetch(relative))
        end

        write_rule_files(files)
      end

      private

      def render_models_reference
        models = context[:models]
        return nil unless models.is_a?(Hash) && !models[:error] && models.any?

        lines = [
          "# ActiveRecord Models (#{models.size})",
          "",
          "> Auto-generated by rails-ai-context. Do not edit manually.",
          "> Check here first for scopes, constants, associations. Read model files for business logic/methods.",
          ""
        ]

        models.keys.sort.first(30).each do |name|
          data = models[name]
          assocs = SectionFacts.associations_list(data).join(", ")
          vals = (data[:validations] || []).size
          line = "- **#{name}**"
          line += " (table: #{data[:table_name]})" if data[:table_name]
          line += " - #{assocs}" unless assocs.empty?
          line += " [#{vals}v]" if vals > 0
          lines << line
          extras = model_extras_line(data)
          lines << extras if extras
        end

        lines << "- _...#{models.size - 30} more_" if models.size > 30
        lines << ""
        lines << "Use `rails_get_model_details(model:\"Name\")` for associations, validations, scopes, enums."
        lines << "Use `rails_get_view(controller:\"name\")` for view templates."
        lines << "Use `rails_get_test_info(model:\"Name\")` for existing model tests."

        lines.join("\n")
      end

      def render_controllers_reference
        data = context[:controllers]
        return nil unless data.is_a?(Hash) && !data[:error]
        controllers = data[:controllers] || {}
        return nil if controllers.empty?

        # Filter out framework-internal controllers
        framework = %w[DeviseController Devise::OmniauthCallbacksController]
        app_controllers = controllers.reject { |name, _| framework.include?(name) }

        lines = [
          "# Controllers (#{app_controllers.size})",
          "",
          "> Auto-generated by rails-ai-context. Do not edit manually.",
          "> Read controller files directly when editing. Use MCP tools for reference only.",
          ""
        ]

        # ApplicationController before_actions
        before_actions = detect_before_actions
        lines << "**Global before_actions:** #{before_actions.join(', ')}" << "" if before_actions.any?

        lines.concat(render_compact_controllers_list(app_controllers, limit: 25, with_actions: true))

        # List service objects
        services = detect_service_files
        lines << "" << "**Services:** #{services.join(', ')}" if services.any?

        # List jobs
        jobs = detect_job_files
        lines << "**Jobs:** #{jobs.join(', ')}" if jobs.any?

        lines << ""
        lines << "Use `rails_get_controllers(controller:\"Name\", action:\"index\")` for one action's source code."
        lines << "Use `rails_get_edit_context(file:\"path\", near:\"keyword\")` for surgical edit context."
        lines << "Use `rails_get_view(controller:\"name\")` for view templates."
        lines << "Use `rails_get_test_info(controller:\"Name\")` for existing controller tests."
        lines << "Use `rails_validate(files:[...])` to check syntax after editing - do NOT re-read files to verify."

        lines.join("\n")
      end
    end
  end
end
