# frozen_string_literal: true

module RailsAiContext
  module Serializers
    # Generates AGENTS.md optimized for OpenCode.
    # In :compact mode (default), produces ≤150 lines with MCP tool references.
    # In :full mode, delegates to MarkdownSerializer with OpenCode header.
    class OpencodeSerializer
      include TestCommandDetection
      include StackOverviewHelper
      include DesignSystemHelper

      attr_reader :context

      def initialize(context)
        @context = context
      end

      def call
        if RailsAiContext.configuration.context_mode == :full
          FullOpencodeSerializer.new(context).call
        else
          render_compact
        end
      end

      private

      def render_compact
        lines = []
        lines.concat(render_header)
        lines.concat(render_stack_overview)
        lines.concat(render_key_models)
        lines.concat(render_notable_gems)
        lines.concat(render_architecture)
        lines.concat(render_ui_patterns)
        lines.concat(render_mcp_guide)
        lines.concat(render_conventions)
        lines.concat(render_commands)
        lines.concat(render_footer)

        # Enforce max lines
        max = RailsAiContext.configuration.claude_max_lines
        if lines.size > max
          lines = lines.first(max - 2)
          lines << ""
          lines << "_Context trimmed. Use MCP tools for full details._"
        end

        lines.join("\n")
      end

      def render_header
        [
          "# #{context[:app_name]} — AI Context",
          "",
          "> Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}",
          "> Generated by rails-ai-context v#{RailsAiContext::VERSION}",
          ""
        ]
      end

      def render_stack_overview
        lines = [ "## Stack" ]

        schema = context[:schema]
        if schema && !schema[:error]
          lines << "- Database: #{schema[:adapter]} — #{schema[:total_tables]} tables"
        end

        models = context[:models]
        if models.is_a?(Hash) && !models[:error]
          lines << "- Models: #{models.size}"
        end

        routes = context[:routes]
        if routes && !routes[:error]
          internal = %w[action_mailbox/ active_storage/ rails/ conductor/ devise/ turbo/]
          app_ctrls = (routes[:by_controller] || {}).keys.reject { |k| internal.any? { |p| k.downcase.start_with?(p) } }
          lines << "- Routes: #{routes[:total_routes]} across #{app_ctrls.size} controllers"
        end

        jobs = context[:jobs]
        if jobs.is_a?(Hash) && !jobs[:error]
          job_count = jobs[:jobs]&.size || 0
          mailer_count = jobs[:mailers]&.size || 0
          channel_count = jobs[:channels]&.size || 0
          parts = []
          parts << "#{job_count} jobs" if job_count > 0
          parts << "#{mailer_count} mailers" if mailer_count > 0
          parts << "#{channel_count} channels" if channel_count > 0
          lines << "- Async: #{parts.join(", ")}" if parts.any?
        end

        migrations = context[:migrations]
        if migrations.is_a?(Hash) && !migrations[:error]
          pending = migrations[:pending]
          lines << "- Migrations: #{migrations[:total]} total, #{pending&.size || 0} pending"
        end

        lines.concat(full_preset_stack_lines)

        lines << ""
        lines
      end

      def render_key_models
        models = context[:models]
        return [] unless models.is_a?(Hash) && !models[:error] && models.any?

        max_show = 15
        lines = [ "## Key models (#{models.size} total)" ]
        models.keys.sort.first(max_show).each do |name|
          data = models[name]
          assoc_count = (data[:associations] || []).size
          val_count = (data[:validations] || []).size
          top_assocs = (data[:associations] || []).map { |a| "#{a[:type]} :#{a[:name]}" }.join(", ")
          line = "- **#{name}**"
          line += " (#{assoc_count}a, #{val_count}v)" if assoc_count > 0 || val_count > 0
          line += " — #{top_assocs}" if top_assocs && !top_assocs.empty?
          lines << line
        end
        lines << "- _...#{models.size - max_show} more (use `rails_get_model_details` tool)_" if models.size > max_show
        lines << ""
        lines
      end

      def render_notable_gems
        gems = context[:gems]
        return [] unless gems.is_a?(Hash) && !gems[:error]
        notable = gems[:notable_gems] || gems[:notable] || gems[:detected] || []
        return [] if notable.empty?

        lines = [ "## Gems" ]
        grouped = notable.group_by { |g| g[:category]&.to_s || "other" }
        grouped.each do |category, gem_list|
          names = gem_list.map { |g| g[:name] }.join(", ")
          lines << "- **#{category}**: #{names}"
        end
        lines << ""
        lines
      end

      def render_architecture
        conv = context[:conventions]
        return [] unless conv.is_a?(Hash) && !conv[:error]

        arch = conv[:architecture] || []
        patterns = conv[:patterns] || []
        return [] if arch.empty? && patterns.empty?

        arch_labels = RailsAiContext::Tools::GetConventions::ARCH_LABELS rescue {}
        pattern_labels = RailsAiContext::Tools::GetConventions::PATTERN_LABELS rescue {}

        lines = [ "## Architecture" ]
        arch.each { |p| lines << "- #{arch_labels[p] || p}" }
        patterns.first(8).each { |p| lines << "- #{pattern_labels[p] || p}" }
        lines << ""
        lines
      end

      def render_ui_patterns
        render_design_system(context, max_lines: 30)
      end

      def render_mcp_guide # rubocop:disable Metrics/MethodLength,Metrics/AbcSize
        [
          "## MCP Tools (25)",
          "",
          "This project has 25 MCP tools available via `rails ai:serve` (configured in `.mcp.json`).",
          "When MCP tools are connected, **prefer them over reading files** — they return only relevant data and save tokens.",
          "If MCP tools are not available, read files directly as usual.",
          "",
          "### What Are You Trying to Do?",
          "",
          "**Understand a feature or area:**",
          "→ `rails_analyze_feature(feature:\"cook\")` — models + controllers + routes + services + jobs + views + tests in one call",
          "→ `rails_get_context(model:\"Cook\")` — schema + model + controller + views assembled together",
          "",
          "**Understand a method (who calls it, what it calls):**",
          "→ `rails_search_code(pattern:\"can_cook?\", match_type:\"trace\")` — definition + source + siblings + all callers + test coverage",
          "",
          "**Add a field or modify a model:**",
          "→ `rails_get_schema(table:\"cooks\")` — columns, types, indexes, defaults, encrypted hints",
          "→ `rails_get_model_details(model:\"Cook\")` — associations, validations, scopes, enums, callbacks, macros",
          "",
          "**Fix a controller bug:**",
          "→ `rails_get_controllers(controller:\"CooksController\", action:\"create\")` — source + inherited filters + render map + side effects + private methods",
          "",
          "**Build or modify a view:**",
          "→ `rails_get_design_system(detail:\"standard\")` — canonical HTML/ERB patterns to copy",
          "→ `rails_get_view(controller:\"cooks\")` — templates with ivars, Turbo wiring, Stimulus refs",
          "→ `rails_get_partial_interface(partial:\"shared/status_badge\")` — what locals to pass",
          "",
          "**Write tests:**",
          "→ `rails_get_test_info(detail:\"standard\")` — framework + fixtures + test template to copy",
          "→ `rails_get_test_info(model:\"Cook\")` — existing tests for a model",
          "",
          "**Find code:**",
          "→ `rails_search_code(pattern:\"has_many\")` — regex search with 2 lines of context",
          "→ `rails_search_code(pattern:\"create\", match_type:\"definition\")` — only `def` lines",
          "→ `rails_search_code(pattern:\"can_cook\", match_type:\"call\")` — only call sites",
          "",
          "**After editing (EVERY time):**",
          "→ `rails_validate(files:[\"app/models/cook.rb\", \"app/views/cooks/new.html.erb\"], level:\"rails\")` — syntax + semantics + security",
          "",
          "### Rules (when MCP is connected)",
          "",
          "1. Prefer MCP tools over reading db/schema.rb, config/routes.rb, model files — they return structured, relevant data",
          "2. Prefer `rails_search_code` over Grep for code search — it supports trace mode and smart context",
          "3. Prefer `rails_validate` over `ruby -c` or `erb` — it includes semantic + security checks",
          "4. Read files when you need to Edit them, or when MCP tools are not available",
          "5. Start with `detail:\"summary\"` to orient, then drill into specifics",
          "",
          "### All 25 Tools",
          "",
          "| Tool | What it does |",
          "|------|-------------|",
          "| `rails_analyze_feature(feature:\"X\")` | Full-stack: models + controllers (inherited filters) + routes (helpers) + services + jobs + views + tests + gaps |",
          "| `rails_get_context(model:\"X\")` | Composite: schema + model + controller + routes + views in one call |",
          "| `rails_search_code(pattern:\"X\", match_type:\"trace\")` | Trace: definition + class context + source + siblings + callers + test coverage |",
          "| `rails_get_controllers(controller:\"X\", action:\"Y\")` | Action source + inherited filters + render map + side effects + private methods |",
          "| `rails_validate(files:[...], level:\"rails\")` | Syntax + semantic validation + Brakeman security (if installed) |",
          "| `rails_get_schema(table:\"X\")` | Columns with [indexed]/[unique]/[encrypted]/[default] + orphaned table warnings |",
          "| `rails_get_model_details(model:\"X\")` | Associations, validations, scopes (with body), enums (with backing type), macros, delegations |",
          "| `rails_get_routes(controller:\"X\")` | Routes with code-ready helpers (`cook_path(@record)`) and controller filters inline |",
          "| `rails_get_view(controller:\"X\")` | Templates with ivars, Turbo Frame/Stream IDs, Stimulus refs, partial locals |",
          "| `rails_get_design_system` | Canonical HTML/ERB copy-paste patterns for buttons, inputs, cards, modals |",
          "| `rails_get_stimulus(controller:\"X\")` | Targets, values, actions + copy-paste HTML data-attributes + reverse view lookup |",
          "| `rails_get_test_info(model:\"X\")` | Existing tests + fixture contents with relationships + test template |",
          "| `rails_get_concern(name:\"X\", detail:\"full\")` | Concern methods with full source code + which models include it |",
          "| `rails_get_callbacks(model:\"X\")` | Callbacks in Rails execution order with source |",
          "| `rails_get_edit_context(file:\"X\", near:\"Y\")` | Code around a match with class/method context + line numbers |",
          "| `rails_search_code(pattern:\"X\")` | Regex search with smart limiting + `exclude_tests` + `group_by_file` + pagination |",
          "| `rails_get_service_pattern` | Service objects: interface, dependencies, side effects, callers |",
          "| `rails_get_job_pattern` | Jobs: queue, retries, guard clauses, broadcasts, schedules |",
          "| `rails_get_env` | Environment variables + credentials keys (not values) + external services |",
          "| `rails_get_partial_interface(partial:\"X\")` | Partial locals contract: what to pass + usage examples |",
          "| `rails_get_turbo_map` | Turbo Stream/Frame wiring: broadcasts → subscriptions + mismatch warnings |",
          "| `rails_get_helper_methods` | App + framework helper methods with view cross-references |",
          "| `rails_get_config` | Database adapter, auth framework, assets stack, cache, queue, Action Cable |",
          "| `rails_get_gems` | Notable gems with versions, categories, config file locations |",
          "| `rails_get_conventions` | App patterns: auth checks, flash messages, create action template, test patterns |",
          "| `rails_security_scan` | Brakeman static analysis: SQL injection, XSS, mass assignment |",
          ""
        ]
      end

      def render_conventions
        conv = context[:conventions]
        return [] unless conv.is_a?(Hash) && !conv[:error]

        config_files = conv[:config_files] || []
        return [] if config_files.empty?

        lines = [ "## Key config files" ]
        config_files.first(5).each { |f| lines << "- `#{f}`" }
        lines << ""
        lines
      end

      def render_commands
        test_cmd = detect_test_command
        [
          "## Commands",
          "- `bin/dev` — start dev server",
          "- `#{test_cmd}` — run tests",
          "- `rails db:migrate` — run pending migrations",
          ""
        ]
      end

      def render_footer
        [
          "## Rules",
          "- Follow existing patterns and conventions",
          "- Use the MCP tools to check schema before writing migrations",
          "- Match existing code style",
          "- Run tests after changes",
          ""
        ]
      end
    end

    # Internal: full-mode OpenCode serializer (wraps MarkdownSerializer)
    class FullOpencodeSerializer < MarkdownSerializer
      include TestCommandDetection

      private

      def header
        <<~MD
          # #{context[:app_name]} — AI Context

          > Auto-generated by rails-ai-context v#{RailsAiContext::VERSION}
          > Generated: #{context[:generated_at]}
          > Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}

          This file gives OpenCode deep context about this Rails application's
          structure, patterns, and conventions.
        MD
      end

      def footer
        rules = []
        rules << "## Behavioral Rules"
        rules << ""
        rules << "When working in this codebase:"
        rules << "- Follow existing patterns and conventions detected above"
        rules << "- Use the database schema as the source of truth for column names and types"
        rules << "- Respect existing associations and validations when modifying models"
        rules << "- Match the project's architecture style (#{architecture_summary})" if architecture_summary
        test_cmd = detect_test_command
        rules << "- Run `#{test_cmd}` after making changes to verify correctness"
        rules << ""
        rules << super
        rules.join("\n")
      end

      def architecture_summary
        arch = context.dig(:conventions, :architecture)
        arch&.any? ? arch.join(", ") : nil
      end
    end
  end
end
