# frozen_string_literal: true

module RailsAiContext
  module Serializers
    # Generates AGENTS.md optimized for OpenCode.
    # In :compact mode (default), produces ≤150 lines with MCP tool references.
    # In :full mode, delegates to MarkdownSerializer with OpenCode header.
    class OpencodeSerializer
      include TestCommandDetection
      include StackOverviewHelper
      include ToolGuideHelper
      include CompactSerializerHelper
      include ContextModeDispatch

      private

      def full_serializer_class
        FullOpencodeSerializer
      end

      # The shared architecture and footer renderers serve here too; the
      # overrides this class used to carry dropped the Services/Jobs lines
      # and the detected test command, and its composition skipped the
      # warnings, so a half-failed run looked clean in AGENTS.md.
      def render_compact
        lines = []
        lines.concat(render_header)
        lines.concat(render_stack_overview)
        lines.concat(render_key_models)
        lines.concat(render_notable_gems)
        lines.concat(render_architecture)
        lines.concat(render_commands)
        lines.concat(render_tools_guide_compact)
        lines.concat(render_warnings)
        lines.concat(render_footer)

        enforce_max_lines(lines)
      end
    end

    # Internal: full-mode OpenCode serializer (wraps MarkdownSerializer)
    class FullOpencodeSerializer < MarkdownSerializer
      include FullSerializerBehavior

      private

      def header
        <<~MD
          # #{context[:app_name]} - AI Context

          > Auto-generated by rails-ai-context v#{RailsAiContext::VERSION}
          > Generated: #{context[:generated_at]}
          > Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}

          This file gives OpenCode deep context about this Rails application's
          structure, patterns, and conventions.
        MD
      end
    end
  end
end
