# frozen_string_literal: true

module RailsAiContext
  module Serializers
    # Generates AGENTS.md optimized for OpenCode.
    # In :compact mode (default), produces ≤150 lines with MCP tool references.
    # In :full mode, delegates to MarkdownSerializer with OpenCode header.
    class OpencodeSerializer < Base
      include TestCommandDetection
      include StackOverviewHelper
      include ToolGuideHelper
      include CompactSerializerHelper
      include ContextModeDispatch

      private

      def full_serializer_class
        FullOpencodeSerializer
      end

      def render_compact
        render_compact_rules
      end
    end

    # Internal: full-mode OpenCode serializer (wraps MarkdownSerializer)
    class FullOpencodeSerializer < MarkdownSerializer
      include FullSerializerBehavior

      private

      def header
        <<~MD
          # #{context[:app_name]} - AI Context

          > Auto-generated by rails-ai-context v#{RailsAiContext::VERSION}
          > Generated: #{context[:generated_at]}
          > Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}
          #{tier_note}
          This file gives OpenCode deep context about this Rails application's
          structure, patterns, and conventions.
        MD
      end
    end
  end
end
