# frozen_string_literal: true

module RailsAiContext
  module Serializers
    # Shared writer that wraps content in `<!-- BEGIN/END rails-ai-context -->`
    # markers so user-added content OUTSIDE the markers survives regeneration.
    #
    # Used by ContextFileSerializer (for CLAUDE.md, AGENTS.md, .github/copilot-
    # instructions.md), CursorRulesSerializer (for .cursorrules) and, for a
    # per-directory AGENTS.md the user wrote, OpencodeRulesSerializer. Same
    # marker contract everywhere - a user can hand-write content above or below
    # the gem-managed block and it'll persist across `rails ai:context` runs.
    module SectionMarkerWriter
      BEGIN_MARKER = "<!-- BEGIN rails-ai-context -->"
      END_MARKER   = "<!-- END rails-ai-context -->"

      # Both markers are non-blank lines of the managed block, so the compact budget counts them.
      MARKER_LINES = 2

      # The full-mode header carries the run's own clock, so a run that found
      # nothing new still put a diff in a repo that commits its context files.
      GENERATED_LINE = /^> Generated: .*\n/

      BLOCK = /#{Regexp.escape(BEGIN_MARKER)}.*?#{Regexp.escape(END_MARKER)}\n?/m

      # Why a run left a file alone: with a marker lost, or a second block
      # pasted in, nothing says where the gem's block ends.
      UNPAIRED = "unpaired rails-ai-context marker, left as it is"

      # Inside a file somebody else wrote, the note claims the block rather
      # than the whole file, as Install::Cleanup::GENERATED_NOTE does.
      BLOCK_NOTE = "This block is generated by rails-ai-context and rewritten on every run. " \
        "Edit outside its BEGIN/END markers."

      module_function

      # A file under a name users write by hand too (OpenCode's
      # app/models/AGENTS.md), rendered whole with the generated note. One
      # that is missing, or that this gem generated whole - the note and no
      # marker - is written whole. Any other is somebody's own, and gets the
      # content as a block the way a root file does, so their text stays and
      # Install::Cleanup takes out only the block.
      def write_whole_or_block(filepath, content)
        existing = File.exist?(filepath) ? RailsAiContext::SafeFile.read_text(filepath) : nil
        return write_whole(filepath, content) if existing.nil? || generated_whole?(existing)

        write_with_markers(filepath, content.sub(Install::Cleanup::GENERATED_LINE, "> #{BLOCK_NOTE}"))
      end

      def generated_whole?(text)
        markers(text) == :none && text.match?(Install::Cleanup::GENERATED_LINE)
      end

      # A file the gem owns whole, rewritten only when it says something else.
      def write_whole(filepath, content)
        return :skipped if File.exist?(filepath) && RailsAiContext::SafeFile.read_text(filepath) == content

        atomic_write(filepath, content)
        :written
      end

      # Write `content` to `filepath` wrapped in markers. If the file already
      # exists with markers, replace only the marker block (preserving user
      # content outside). If the file exists WITHOUT markers, prepend the
      # marker block so AI tools read our context first while keeping the
      # user's prior content intact below. A file whose markers do not pair
      # up is not written: replacing a guess at the block could take the
      # user's text, and prepending a new one duplicated the old for good.
      #
      # Returns :written if the file changed (created or block updated),
      # :skipped if the file already had the exact same marker block,
      # :unpaired if its markers do not pair up.
      def write_with_markers(filepath, content)
        marked_content = "#{BEGIN_MARKER}\n#{content}\n#{END_MARKER}\n"

        if File.exist?(filepath)
          # Read as UTF-8 whatever the locale: a C locale tagged it US-ASCII,
          # and the first non-ASCII character stopped the rewrite. A file that
          # is no UTF-8 keeps its bytes, and the block joins them as bytes.
          existing = RailsAiContext::SafeFile.read_text(filepath)
          marked_content = marked_content.b if existing.encoding == Encoding::BINARY

          new_content = case markers(existing)
          # A block, so a backslash in the content is not read as a backreference.
          when :pair then existing.sub(BLOCK) { marked_content }
          when :none then "#{marked_content}\n#{existing}"
          else return :unpaired
          end

          return :skipped if same_but_for_timestamp?(existing, new_content)

          atomic_write(filepath, new_content)
          :written
        else
          atomic_write(filepath, marked_content)
          :written
        end
      end

      # :pair for one BEGIN marker before one END marker, :none for neither,
      # :unpaired for anything else: a lone marker, two blocks, END first.
      def markers(text)
        begins = text.scan(BEGIN_MARKER).size
        ends = text.scan(END_MARKER).size
        return :none if begins.zero? && ends.zero?
        return :pair if begins == 1 && ends == 1 && text.index(BEGIN_MARKER) < text.index(END_MARKER)

        :unpaired
      end

      # Files a write's outcome under the bucket a context run reports it in.
      def report(outcome, filepath, result)
        case outcome
        when :written then result[:written] << filepath
        when :skipped then result[:skipped] << filepath
        when :unpaired then result[:not_applicable][filepath] = UNPAIRED
        end
        result
      end

      def same_but_for_timestamp?(existing, candidate)
        existing == candidate ||
          existing.gsub(GENERATED_LINE, "") == candidate.gsub(GENERATED_LINE, "")
      end

      def atomic_write(filepath, content)
        RailsAiContext::SafeFile.atomic_write(filepath, content)
      end
    end
  end
end
